# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems: [jekyll-paginate, jekyll-gist, jemoji]

# Site settings
title: "Aldo Ridhoni"
tagline: "Belajar Menulis"
description: > # this means to ignore newlines until "email:"
   A Weblog - Aldo Ridhoni

email: aldoridhoni@gmail.com
# blog cover
cover: "//static.aldoridhoni.com/blog/covers/doodle.jpg"

name: 'Aldo Ridhoni'
author: 'Aldo Ridhoni'
author_image: "/assets/images/author.jpg"
version: '08.16'
paginate:	5
github:
  repo: https://github.com/aldoridhoni/weblog/
url: "https://blog.aldoridhoni.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/aldoridho
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
